# Generated by Django 5.2.5 on 2025-11-05 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_address_user_blood_group_user_emergency_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('score', models.IntegerField()),
                ('risk_level', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_scores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
