services:
  db:
    image: postgres:17
    container_name: sahasi-postgres
    environment:
      POSTGRES_DB: sahasi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      # - .:/code
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      DOCKER_ENV: "true"
    depends_on:
      - db

volumes:
  postgres_data:
