// sharedStyles.js
import { StyleSheet } from 'react-native';

export const sharedStyles = StyleSheet.create({
  safeArea: { flex: 1 },
  scrollView: { flex: 1 },
  contentContainer: { paddingBottom: 40 },
  screenHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  backButton: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  screenTitle: { fontSize: 18, fontWeight: '700' },
  placeholder: { width: 40 },
  addButton: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  formSection: { paddingHorizontal: 16, marginBottom: 16 },
  inputGroup: { marginBottom: 16 },
  label: { fontSize: 14, fontWeight: '600', marginBottom: 8 },
  input: { borderWidth: 1, borderRadius: 8, paddingHorizontal: 16, paddingVertical: 12, fontSize: 16 },
  selectInput: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  selectText: { fontSize: 16 },
  sectionTitle: { fontSize: 16, fontWeight: '700', marginBottom: 16 },
  infoCard: { flexDirection: 'row', alignItems: 'center', padding: 16, borderRadius: 12, marginHorizontal: 16, marginBottom: 24 },
  infoText: { flex: 1, fontSize: 14, marginLeft: 12, lineHeight: 20 },
  saveButton: { backgroundColor: '#22C55E', borderRadius: 8, paddingVertical: 14, marginHorizontal: 16, alignItems: 'center', marginTop: 8, marginBottom: 24 },
  saveButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '700' },
  testButton: { backgroundColor: '#3B82F6', borderRadius: 8, paddingVertical: 14, marginHorizontal: 16, alignItems: 'center', marginTop: 8, marginBottom: 12, flexDirection: 'row', justifyContent: 'center' },
  testButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '700', marginLeft: 8 },
  toggleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 16, borderRadius: 12, borderWidth: 1, marginBottom: 12 },
  toggleLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  toggleTextContainer: { marginLeft: 12, flex: 1 },
  toggleTitle: { fontSize: 16, fontWeight: '600', marginBottom: 2 },
  toggleDescription: { fontSize: 13 },
  contactsList: { paddingHorizontal: 16 },
  contactCard: { borderRadius: 12, padding: 16, marginBottom: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  contactLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  contactAvatar: { width: 56, height: 56, borderRadius: 28, alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  contactInfo: { flex: 1 },
  contactName: { fontSize: 16, fontWeight: '700', marginBottom: 4 },
  contactPhone: { fontSize: 14, marginBottom: 2 },
  contactRelation: { fontSize: 12 },
  contactActions: { flexDirection: 'row', gap: 8 },
  actionButton: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  emptyState: { alignItems: 'center', justifyContent: 'center', paddingVertical: 64 },
  emptyText: { fontSize: 16, marginTop: 16, marginBottom: 24 },
  addContactButton: { backgroundColor: '#22C55E', flexDirection: 'row', alignItems: 'center', paddingVertical: 12, paddingHorizontal: 24, borderRadius: 8 },
  addContactButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '700', marginLeft: 8 },
  welcomeSection: { alignItems: 'center', paddingVertical: 32, paddingHorizontal: 16 },
  logoContainer: { width: 96, height: 96, borderRadius: 48, alignItems: 'center', justifyContent: 'center', marginBottom: 16 },
  appTitle: { fontSize: 24, fontWeight: '700', marginBottom: 8 },
  appSubtitle: { fontSize: 14, textAlign: 'center', lineHeight: 20 },
  featuresSection: { paddingHorizontal: 16, marginBottom: 24 },
  featureCard: { flexDirection: 'row', padding: 16, borderRadius: 12, marginBottom: 16 },
  featureIcon: { width: 56, height: 56, borderRadius: 28, alignItems: 'center', justifyContent: 'center', marginRight: 16 },
  featureContent: { flex: 1 },
  featureTitle: { fontSize: 16, fontWeight: '700', marginBottom: 6 },
  featureDescription: { fontSize: 14, lineHeight: 20 },
  emergencySection: { paddingHorizontal: 16, marginBottom: 24 },
  emergencyCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 16, borderRadius: 12, borderWidth: 1, marginBottom: 12 },
  emergencyLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  emergencyNumberBadge: { backgroundColor: '#22C55E', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, marginRight: 12 },
  emergencyNumber: { color: '#FFFFFF', fontSize: 18, fontWeight: '700' },
  emergencyInfo: { flex: 1 },
  emergencyTitle: { fontSize: 16, fontWeight: '700', marginBottom: 2 },
  emergencyDescription: { fontSize: 13 },
  tipCard: { padding: 16, borderRadius: 12 },
  tipHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  tipTitle: { fontSize: 18, fontWeight: '700', marginLeft: 12 },
  tipsList: { gap: 12 },
  tipItem: { flexDirection: 'row', alignItems: 'flex-start' },
  tipText: { flex: 1, fontSize: 14, marginLeft: 12, lineHeight: 20 },
  supportSection: { paddingHorizontal: 16, marginBottom: 24 },
  supportCard: { flexDirection: 'row', alignItems: 'center', padding: 16, borderRadius: 12, borderWidth: 1 },
  supportInfo: { flex: 1, marginLeft: 16 },
  supportTitle: { fontSize: 16, fontWeight: '700', marginBottom: 4 },
  supportDescription: { fontSize: 13 },
  versionSection: { alignItems: 'center', paddingVertical: 24 },
  versionText: { fontSize: 12, marginBottom: 4 },
});
